### PR TITLE
custom fees

### PR DESCRIPTION
**Pull request by djpnewton**
- allow adjusting the fee for single signers
- allow choosing a custom fee

builds on #20

### CODE REVIEW

**Comment by KayBeSee** [comment]
Do you mind merging the current master so that diff doesn't include stuff from #20?

**Comment by djpnewton** [comment]
no problem, done

**Comment by KayBeSee** [comment]
I just made a PR in your branch updating the UI around custom fees. It gives the modal another view when inputting a custom fee that is a little less confusing.

Do you mind also replacing the earn.com fee estimator with `https://mempool.space/api/v1/fees/recommended`?

Besides that, this is great and a high-value contribution.

**Comment by djpnewton** [comment]
all done

**Comment by KayBeSee** [comment]
Fixes #9

**Pull request merged**
