### PR TITLE
Testnet

### PR DESCRIPTION
**Pull request by djpnewton**
added --testnet and --devurl command line parameters to try and make testing easier

also adding 'testnet' to UI when in testnet mode and add testnet to the downloaded config files

addresses #8

### CODE REVIEW

**Comment by KayBeSee** [comment]
This looks great, thank you so much for taking the time to implement this.

I just did a fast glance (haven't tasted on HWW yet) and noticed a few things:

1. The derivationPaths in [`getChildPubKeyFromXpub`](https://github.com/KayBeSee/lily-wallet/pull/20/files#diff-657a98d8b272d6520223a2c66b36b670L107) need to be modified for testnet. They should be m/49'/1'/0'/.... and m/84'/1'/0'/.... 

2. When importing devices, their derivationPaths should also be modified ([here](https://github.com/KayBeSee/lily-wallet/pull/20/files#diff-1891f2d8aa9dd41f3c13ea989081f032L50) and [here](https://github.com/KayBeSee/lily-wallet/pull/20/files#diff-1891f2d8aa9dd41f3c13ea989081f032L74))

3. The [`createColdCardBlob`](https://github.com/KayBeSee/lily-wallet/pull/20/files#diff-27f3096fd3707252dc86c54cd3cf90cfL134) function should also have the derivation path modified.

It might be nice to just create a new function that takes the addressType, bip32Path, and currentBitcoinNetwork, and spits out the full path. I apologize on the naming in that function...there's a lot of repetition. Should be like "fullPath" and "pathPrefix" and "pathSuffix" or something.

The reason for the split is that you need to give the hardware devices the full path, pubkey, and masterfingerprint for them to be able to sign but unchained's deriveChildPublicKey takes the xpub from m/x'/x'/x' and a path to produce the public key.

Besides those, I don't see anything else that needs modified. I tried it out with a new software wallet and received and sent no problem 👍

**Comment by KayBeSee** [comment]
Do you mind removing the package for handling environment variables too?  Just trying to keep the build size as small as possible. If there is an advantage of using it over native node environment variables (i.e. `TESTNET=TRUE DEVURL=TRUE yarn electron`) I'm open to keeping it.

**Comment by djpnewton** [comment]
I think this is working ok now

**Comment by KayBeSee** [comment]
Just went through and tested this and it all works great except for one edge-case with using a single hardware wallet.

It looks like we need to specify the current network [here](https://github.com/KayBeSee/lily-wallet/pull/20/files#diff-657a98d8b272d6520223a2c66b36b670R175).

Should be:

```
if (addressType === 'p2sh') {
    address = payments.p2sh({
      redeem: payments.p2wpkh({
        pubkey: Buffer.from(childPubKey.childPubKey, 'hex'),
        network: currentBitcoinNetwork
      }),
      network: currentBitcoinNetwork
    });
  } else { // p2wpkh
```

besides that, I think we're good!

**Comment by KayBeSee** [comment]
Not sure if that link worked, but it's line 175 in the `getAddressFromPubKey` function

**Comment by djpnewton** [comment]
ok cool, i think that did it

**Comment by KayBeSee** [comment]
Looks good!

**Pull request merged**
