### PR TITLE
send the '--testnet' param to HWI when using a testnet wallet

### PR DESCRIPTION
**Pull request by djpnewton**
I missed this earlier

### CODE REVIEW

**Comment by djpnewton** [comment]
@KayBeSee  I think this is important for hardware wallets to work when in testnet mode

**Comment by KayBeSee** [comment]
Can you link to some documentation in HWI? What exactly does this flag do?

**Comment by djpnewton** [comment]
There is not much documentation: https://github.com/bitcoin-core/HWI/blob/2b8102e06a094bc150bcbd4b233819f350e44c9e/hwilib/cli.py#L124

It changes the type of xpub retrieved from the device (xpub vs tpub), I assume it changes the type of address returned by  'displayaddress'

Maybe it is not required for 'signtx'

**Comment by KayBeSee** [comment]
Interesting. Ok, merged.

**Pull request merged**
