### PR TITLE
feature: adds a password confirmation field to help prevent typos in …

### PR DESCRIPTION
**Pull request by bilthon**
This is just a simple change intended to avoid users encrypting their configuration file with a mistyped password. Maybe the minimum password length of 3 could be raised to something like 8 or 9 ?

### CODE REVIEW

**Comment by djpnewton** [comment]
This is a good feature.

two suggestions:

- add the validation failure reasons to the UI (like https://github.com/KayBeSee/lily-wallet/blob/c274908f6b13cea47d5b099828fb738ea6f86fdf/src/pages/Send/index.js#L320)

- restore the `onInputEnter` functionality to the confirmation input so the user can advance to the next page with the enter key again

**Comment by bilthon** [comment]
Ok done. The "enter" key moves the user from the "password" to the "confirmation" and from there to the save button. And also error messages are shown below each one of the fields in order to tell the user what's wrong when there is something wrong.

**Comment by djpnewton** [comment]
@KayBeSee do you think this is ok to merge?

**Comment by KayBeSee** [comment]
Yeah, looks good!

**Pull request merged**
